### ISSUE TITLE
Problem parsing mgp4 vcfs

### ISSUE THREAD

**Issue by mimi31k** [jaxcs/Seqnature#2]
Hi,
There seems to be an issue when constructing genome sequences with the current mgp.v4 vcfs. The script does not deal with lines where there is a "./." instead of "0/0"

modifying the vcf file to replace "./." with "0/0" works but it would be nice to get a fix in the script...

Thanks!

error message is as below:

Traceback (most recent call last):
  File "/home/mliang/mdwilson/external/Seqnature/build_new_sequence_from_vcfs.py", line 755, in <module>
    main()
  File "/home/mliang/mdwilson/external/Seqnature/build_new_sequence_from_vcfs.py", line 746, in main
    s_columns)
  File "/home/mliang/mdwilson/external/Seqnature/build_new_sequence_from_vcfs.py", line 586, in process_remaining
    event = Snp(f, strain_col, columns)
  File "/home/mliang/mdwilson/external/Seqnature/build_new_sequence_from_vcfs.py", line 354, in __init__
    which_allele = int(alleles[0]) - 1
ValueError: invalid literal for int() with base 10: '.'

**Comment by AlSimonsJax** [comment]
It would really be nice if Sanger would stop changing their formats!  Ilk get a fix in next week.

Thanks for reporting it.
Al



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by mimi31k** [comment]
Thanks!
I figured an easier workaround is to change the conditional statement in the Indel and Snp class from 
parts[haplotype_column] == '.' to
parts[haplotype_column].startswith('.')
